name: Java CI with Maven
 
on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: Build, Test Java Project
    runs-on: ubuntu-latest  

    steps:
     
      - name: Check code
        uses: actions/checkout@v4  
     
      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'  

      - name:  Maven
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=tpintegrationcontinue-HAZOURLIMohamedMehdi
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}  

      - name: Build Maven
        run: mvn -B package  
